// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const   web = FirebaseOptions(
    apiKey: 'AIzaSyBMGDcxoojihBxm80koU_hff4vVqptCJF4',
    appId: '1:187346416545:web:3f2b5a808d983a83c691e0',
    messagingSenderId: '187346416545',
    projectId: 'salama-ad405',
    authDomain: 'salama-ad405.firebaseapp.com',
    storageBucket: 'salama-ad405.appspot.com',
    measurementId: 'G-4J3EB586K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB68OkU94ATI3ygvWfQ7Pb_UrbK_TfDeXU',
    appId: '1:187346416545:android:28e7c8469ffb60bfc691e0',
    messagingSenderId: '187346416545',
    projectId: 'salama-ad405',
    storageBucket: 'salama-ad405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDcsWQ-rRd86GREQ_2es4HcFzw016g5sU',
    appId: '1:187346416545:ios:50970c8e2a73069cc691e0',
    messagingSenderId: '187346416545',
    projectId: 'salama-ad405',
    storageBucket: 'salama-ad405.appspot.com',
    iosBundleId: 'com.salamah.app.salamah',
  );
}
